package modelrepo

import "strings"

// ScriptedTestBackendType is the in-binary test backend: its replies are replayed from a script file, never generated by a model.
const ScriptedTestBackendType = "scripted-test"

// CanonicalBackendType maps compatibility backend keywords to the implementation
// type used by the runtime by lowercasing and trimming the input.
func CanonicalBackendType(backendType string) string {
	return strings.ToLower(strings.TrimSpace(backendType))
}
