services:
  runtime-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: contenox/runtime-api:local
    environment:
      - DATABASE_URL=postgres://username:password@postgres:5432/postgres?sslmode=disable
      - PORT=8080
      - NATS_URL=nats://natsuser:natspassword@nats:4222
      - NATS_USER=natsuser
      - NATS_PASSWORD=natspassword
      - TOKENIZER_SERVICE_URL=http://tokenizer:50051
      - EMBED_MODEL=${EMBED_MODEL}
      - EMBED_PROVIDER=${EMBED_PROVIDER}
      - EMBED_MODEL_CONTEXT_LENGTH=${EMBED_MODEL_CONTEXT_LENGTH}
      - TASK_MODEL=${TASK_MODEL}
      - TASK_MODEL_CONTEXT_LENGTH=${TASK_MODEL_CONTEXT_LENGTH}
      - TASK_PROVIDER=${TASK_PROVIDER}
      - CHAT_MODEL=${CHAT_MODEL}
      - CHAT_MODEL_CONTEXT_LENGTH=${CHAT_MODEL_CONTEXT_LENGTH}
      - CHAT_PROVIDER=${CHAT_PROVIDER}
