// The one-paragraph product description. It is the first thing a model reads in
// both /llms.txt and /llms-full.txt, so it lives here once rather than being
// kept in sync by hand in two route files.
export const PRODUCT_SUMMARY =
  'Declare an agent in one Markdown file. Run it in your terminal. Every action it takes is checked against policy you wrote — and when it needs you, it waits, durably: answer from your terminal or your phone, days later, and the run resumes exactly once. A declaration is Markdown with a YAML frontmatter header in `.contenox/agents/`, naming the tools it may call and the model, with a body that becomes its system prompt; a directory of declarations is a workflow, where the `agent.md` at the top reads the request and routes to the branch beneath it. contenox reads the declarations you already keep for Claude Code, Copilot, Cursor, OpenCode and Antigravity, where they are — nothing to move or convert. It compiles each one into the chain that runs it and the policy it runs under, in `.generated/`: both JSON Schema-validated, neither hand-maintained. You bring the tools, and only the ones you need: every tool an agent carries is tokens spent on every turn and one more thing to govern. The client in front of a session provides `fs/*` and `terminal/*` as negotiated capabilities and contenox forwards to them, or you attach MCP servers and OpenAPI services and decide what each may do. Every call crosses that one tool boundary and is checked against your policy before it runs, and a run that stops for a human checkpoints, releases the process, survives a restart, and resumes exactly once when the answer arrives — hours or days later, from anywhere. Open source under Apache-2.0, one binary, no account, on your own machine, on any AI model you pick.';

// The three shapes contenox runs in, partitioned by who is accountable for the
// machine. Stated right after the summary in both files.
export const PRODUCT_SHAPES =
  'Three shapes, partitioned by who is accountable for the machine. `contenox beam` is the front door: the first-party terminal client, a person at their own keyboard, with the filesystem and terminal working natively and gated calls raising an approval card inline — bare `contenox` on a terminal opens it. `contenox run [agent] "task"` is the scripting shape: a program is the caller (CI, cron, another agent), the report goes to stdout, exit 0 on success. `contenox serve` is the organization\'s shape: a standing host serving one workspace fixed at launch, with no filesystem and no terminal tools at all — every capability is an MCP server — driven by connectors and event triggers through the relay, optionally on Postgres/NATS/Valkey. Editors (Zed, JetBrains, AionUi, OpenClaw) spawn `contenox acp` over stdio, and per that protocol the editor owns the workspace. One instance serves exactly one workspace, fixed at launch; there is no workspace selection anywhere, and clients discover instances and their sessions instead.';
