// The one-paragraph product description. It is the first thing a model reads in
// both /llms.txt and /llms-full.txt, so it lives here once rather than being
// kept in sync by hand in two route files.
export const PRODUCT_SUMMARY =
  'An agent server. Before Apache, serving a website meant writing your own server; Apache made serving something you install, and HTML the thing you author. contenox does that for agents: the harness — the loop, the tool gate, the approval flow, session persistence — is infrastructure you install, and the agent is a file you declare. A declaration is Markdown with a YAML frontmatter header in `.contenox/agents/`, naming the tools it may call and the model, with a body that becomes its system prompt; a directory of declarations is a workflow, where the `agent.md` at the top reads the request and routes to the branch beneath it. contenox reads the declarations you already keep for Claude Code, Copilot, Cursor, OpenCode and Antigravity, where they are — nothing to move or convert. It compiles each one into the chain that runs it and the policy it runs under, in `.generated/`: both JSON Schema-validated, neither hand-maintained. You bring the tools, and only the ones you need: every tool an agent carries is tokens spent on every turn and one more thing to govern. An ACP client (your editor) provides `fs/*` and `terminal/*` as negotiated capabilities and contenox forwards to them, or you attach MCP servers and OpenAPI services and decide what each may do. Every call crosses that one tool boundary and is checked against your policy before it runs, and a run that stops for a human checkpoints, releases the process, survives a restart, and resumes exactly once when the answer arrives — hours or days later, from anywhere. Open source under Apache-2.0, one binary, no account, on your own machine, on any AI model you pick.';

// The two ways contenox is deployed. Stated right after the summary in both files.
export const PRODUCT_SHAPES =
  'Two deployment shapes: an editor launches contenox as an ACP subprocess over stdio and `/pair` makes that session reachable from the app; or `contenox serve` runs it as a host with no editor in front of it, against operator-attached MCP.';
